### PR TITLE
add carthage support and use promises

### PR DESCRIPTION
**Pull request by sync**
- [x] Carthage support
- [x] handle errors using promises
- [x] write tests where possible

### CODE REVIEW

**Comment by evgenyneu** [comment]
Very cool, one question - is the readme up to date?

**Comment by sync** [comment]
README is up to date now

**Comment by evgenyneu** [comment]
I can't find the new API with future in the readme: https://github.com/exchangegroup/load-facebook-profile-ios-swift/blob/feature/carthage-and-future/README.md

Do we need to add it there for other people?

**Comment by sync** [comment]
https://github.com/exchangegroup/load-facebook-profile-ios-swift/blob/feature/carthage-and-future/README.md

**Comment by evgenyneu** [comment]
:rocket:

**Pull request merged**
